"""Pulumi entry point for the Qdrant Cloud cluster (control plane).

Manages the cluster + a database API key as IaC, for parity with the other
deployers. It does NOT manage collections — those are defined in
``backend/qdrant/schema.py`` and reconciled by ``python -m qdrant.sync``
(the ``qdrant_sync`` job in .github/workflows/deploy.yml).

Provider auth (see README): the Qdrant Cloud API key + account id come from
provider config / env, not from this file. Before the first ``pulumi up`` the
EXISTING cluster must be imported (``pulumi import``) or Pulumi will create a
second cluster and orphan the live data.

NOTE: the Qdrant Cloud provider is Terraform-bridged; its Python SDK is
generated by ``pulumi package add`` (README). The exact symbol names below
(data-source accessor, resource args) should be confirmed against the
generated SDK once it exists.
"""

from __future__ import annotations

import logging

import pulumi
import pulumi_qdrant_cloud as qdrant_cloud

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s %(message)s",
)

config = pulumi.Config()

# Where the cluster lives + how it is sized. Defaults match the current cluster
# (GCP europe-west3). Override per stack via `pulumi config set`.
cloud_provider = config.get("cloudProvider") or "gcp"
cloud_region = config.get("cloudRegion") or "europe-west3"
cluster_name = config.get("clusterName") or "prediction-market-llm"
number_of_nodes = config.get_int("numberOfNodes") or 1

# Pick the booking package (instance sizing). Prefer an explicit package id from
# config; otherwise fall back to the first package offered for this region.
package_id = config.get("packageId")
if not package_id:
    packages = qdrant_cloud.get_booking_packages(
        cloud_provider=cloud_provider,
        cloud_region=cloud_region,
    )
    package_id = packages.packages[0].id

cluster = qdrant_cloud.AccountsCluster(
    "markets-cluster",
    name=cluster_name,
    cloud_provider=cloud_provider,
    cloud_region=cloud_region,
    configuration={
        "number_of_nodes": number_of_nodes,
        "node_configuration": {"package_id": package_id},
    },
)

# The cluster's data-plane API key (`QDRANT_API_KEY` in GSM) is NOT managed
# here — it was created in the Qdrant Cloud UI when the cluster was provisioned
# and lives in Secret Manager. Managing it from Pulumi would either generate
# a second unused key or require importing the existing one (which Qdrant
# Cloud's API doesn't allow because the key value can't be read back after
# creation). Rotations are a UI-side action.

pulumi.export("cluster_id", cluster.id)
pulumi.export("cluster_url", cluster.url)
